documents: 'src/**/*.{graphql,js,ts,jsx,tsx}'
schema: http://localhost:4000
extensions:
    codegen:
        generates:
            ./schema.graphql:
                plugins:
                    - schema-ast
